spring.application.name=Grapql_demo

spring.datasource.url=jdbc:postgresql://localhost:5432/sentry
spring.datasource.username=sentry
spring.datasource.password=sentry@123
spring.jpa.hibernate.ddl-auto=update